import dotenv from "dotenv";
dotenv.config();

export default {
  MONGO_DATABASE: process.env.MONGO_DATABASE_SHIPMENT,
  MONGO_HOST: process.env.MONGO_HOST_SHIPMENT,
  MONGO_PORT: process.env.MONGO_PORT_SHIPMENT,
  MONGO_INITDB_ROOT_USERNAME: process.env.MONGO_INITDB_ROOT_USERNAME_SHIPMENT,
  MONGO_INITDB_ROOT_PASSWORD: process.env.MONGO_INITDB_ROOT_PASSWORD_SHIPMENT,
  APP_PORT: 4004,
  RABBITMQ_HOST:process.env.RABBITMQ_HOST,
  RABBITMQ_USER:process.env.RABBITMQ_USER,
  RABBITMQ_PASSWORD:process.env.RABBITMQ_PASSWORD,
  RABBITMQ_QUEUE:process.env.RABBITMQ_QUEUE_NOTIFY_WH
};