import dotenv from "dotenv";
dotenv.config();

export default {
  MONGO_DATABASE: process.env.MONGO_DATABASE_RECEIPENT,
  MONGO_HOST: process.env.MONGO_HOST_RECEIPENT,
  MONGO_PORT: process.env.MONGO_PORT_RECEIPENT,
  MONGO_INITDB_ROOT_USERNAME: process.env.MONGO_INITDB_ROOT_USERNAME_RECEIPENT,
  MONGO_INITDB_ROOT_PASSWORD: process.env.MONGO_INITDB_ROOT_PASSWORD_RECEIPENT,
  APP_PORT: 4001,
};